name: Build All Runnable Modules

on:
  push:
    branches-ignore:
      - 'master'
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  build-all:
    name: Build All Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant Execute Permissions for Gradle
        run: chmod +x gradlew

      - name: Clean & Build All Modules
        run: ./gradlew clean build

  android-app:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: build-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Build Android App
        run: ./gradlew :android:app:assembleDebug

      - name: Skip Android App Tests (No Test Execution)
        run: echo "Skipping tests for Android app."

  third-party-library:
    name: Build thirdpartylibrarydependencies
    runs-on: ubuntu-latest
    needs: build-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Build thirdpartylibrarydependencies
        run: ./gradlew :thirdpartylibrarydependencies:assembleDebug

      - name: Skip Tests for thirdparty library (No Test Execution)
        run: echo "Skipping tests for thirdparty library."

  design-pattern:
    name: Build Design Pattern Module
    runs-on: ubuntu-latest
    needs: build-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Build Design Pattern Module
        run: ./gradlew :design_pattern:assembleDebug

      - name: Skip Tests for design pattern module (No Test Execution)
        run: echo "Skipping tests for design pattern module."

  android-test:
    name: Build Android Test Module
    runs-on: ubuntu-latest
    needs: build-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches, ~/.gradle/wrapper
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Build Android Test Module
        run: ./gradlew :android_test:assembleDebug

      - name: Skip Tests for android-test module (No Test Execution)
        run: echo "Skipping tests for android-test module."
